services:
  mecarosmaster:
    build:
      context: ../           # ← racine du projet
      dockerfile: service/mecarosmaster/Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO}
    env_file:
      - ../env/.env
    volumes:
      - ../mecarosmaster_ws:/mecarosmaster_ws
    devices:
      - "${SERIAL_PORT}:${SERIAL_PORT}"
    network_mode: host
    group_add:
      - dialout
    restart: unless-stopped
    tty: true
    stdin_open: true