services:
  mecarosmaster:
    build:
      context: ../
      dockerfile: service/mecarosmaster/Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO}
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    env_file:
      - ../env/.env
    volumes:
      - ../mecarosmaster_ws:/mecarosmaster_ws
    devices:
      - "${SERIAL_PORT}:${SERIAL_PORT}"
    network_mode: host
    group_add:
      - dialout
    restart: unless-stopped
    tty: true
    stdin_open: true